package com.scodeid.kamus.helper;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * @author Created by scode on 30,September,2019
 * Yogi Arif Widodo
 * www.dicoding.com/users/297307
 * www.github.com/yogithesymbian
 * SCODEID company,
 * Indonesia, East Borneo.
 * ==============================================================
 * Android Studio 3.4.2
 * Build #AI-183.6156.11.34.5692245, built on June 27, 2019
 * JRE: 1.8.0_152-release-1343-b16-5323222 amd64
 * JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * Linux 5.2.0-kali2-amd64
 * ==============================================================
 */
public class DatabaseHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME = "dbkamus";
    private static final String SPANYOL = "spanyol";
    private static final String INDONESIA = "indonesia";
    private static final String BALI = "bali";
    private static final String KMS = "kamus";

    public DatabaseHelper(Context context){
        super(context, DATABASE_NAME, null, 1);
    }

    private void createTable(SQLiteDatabase db){
        db.execSQL("DROP TABLE IF EXISTS kamus");
        db.execSQL("CREATE TABLE if not exists kamus (_id INTEGER PRIMARY KEY AUTOINCREMENT, " + " indonesia TEXT, spanyol TEXT, bali TEXT);");
    }

    public void generateData(SQLiteDatabase db){
        ContentValues cv = new ContentValues();
        autoGenerateData(cv, db);
    }

    private void autoGenerateData(ContentValues cv, SQLiteDatabase db) {
        cv.put(INDONESIA,"Adik"); // FIELD 1
        cv.put(SPANYOL,"Hermana");
        cv.put(BALI,"Ari");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Agama");
        cv.put(SPANYOL,"Religion");
        cv.put(BALI,"Ugama");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Air");
        cv.put(SPANYOL,"Agua");
        cv.put(BALI,"Yeh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Angsa"); // FIELD 1
        cv.put(SPANYOL,"Cisne");
        cv.put(BALI,"Bebek");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Anjing"); // FIELD 1
        cv.put(SPANYOL,"Pero");
        cv.put(BALI,"Cicing");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Apa"); // FIELD 1
        cv.put(SPANYOL,"Que");
        cv.put(BALI,"Kenken");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Ayah"); // FIELD 1
        cv.put(SPANYOL,"Padre");
        cv.put(BALI,"Bapa");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Ayam"); // FIELD 1
        cv.put(SPANYOL,"Pollo");
        cv.put(BALI,"Ayam");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"BAB"); // FIELD 1
        cv.put(SPANYOL,"Capitulo");
        cv.put(BALI,"Meju");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Baju"); // FIELD 1
        cv.put(SPANYOL,"La camisa");
        cv.put(BALI,"Baju");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Bandara"); // FIELD 1
        cv.put(SPANYOL,"El aeropuerto");
        cv.put(BALI,"Bandara");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Bangun"); // FIELD 1
        cv.put(SPANYOL,"Laventarse");
        cv.put(BALI,"Bangun");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Baru"); // FIELD 1
        cv.put(SPANYOL,"Nuevo");
        cv.put(BALI,"Sukla");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Beli"); // FIELD 1
        cv.put(SPANYOL,"Comparlo");
        cv.put(BALI,"Tendak");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Belum"); // FIELD 1
        cv.put(SPANYOL,"Aun no");
        cv.put(BALI,"Konden");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Benar"); // FIELD 1
        cv.put(SPANYOL,"Derecho");
        cv.put(BALI,"Beneh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Berapa"); // FIELD 1
        cv.put(SPANYOL,"Cuanto");
        cv.put(BALI,"Kude");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Bercerita"); // FIELD 1
        cv.put(SPANYOL,"Contando historias");
        cv.put(BALI,"Manutur");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Berkata"); // FIELD 1
        cv.put(SPANYOL,"Dijo");
        cv.put(BALI,"Ngorang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Bertengkar"); // FIELD 1
        cv.put(SPANYOL,"Tuve una pelea");
        cv.put(BALI,"Mejagur");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Beruang"); // FIELD 1
        cv.put(SPANYOL,"Uno uso");
        cv.put(BALI,"Beruang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Bibir"); // FIELD 1
        cv.put(SPANYOL,"Labios");
        cv.put(BALI,"Lambe");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Bisa"); // FIELD 1
        cv.put(SPANYOL,"Puede");
        cv.put(BALI,"Midep");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Boleh"); // FIELD 1
        cv.put(SPANYOL,"Mayo");
        cv.put(BALI,"Dados");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Buah");
        cv.put(SPANYOL,"Fruta");
        cv.put(BALI,"Buah");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Buka");
        cv.put(SPANYOL,"Abrelo");
        cv.put(BALI,"Gagah");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Buku"); // FIELD 1
        cv.put(SPANYOL,"Reservar");
        cv.put(BALI,"Buku");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Cabai"); // FIELD 1
        cv.put(SPANYOL,"Chile");
        cv.put(BALI,"Pedes");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Cacing"); // FIELD 1
        cv.put(SPANYOL,"Gusanos");
        cv.put(BALI,"Cacing");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Cantik"); // FIELD 1
        cv.put(SPANYOL,"Bonita");
        cv.put(BALI,"Jegeg");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Celana"); // FIELD 1
        cv.put(SPANYOL,"Pantalones");
        cv.put(BALI,"Celana");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Cicak"); // FIELD 1
        cv.put(SPANYOL,"Lagarto");
        cv.put(BALI,"Cekcek");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Cinta"); // FIELD 1
        cv.put(SPANYOL,"Amor");
        cv.put(BALI,"Semara");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Dari"); // FIELD 1
        cv.put(SPANYOL,"De");
        cv.put(BALI,"Saking");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Diam"); // FIELD 1
        cv.put(SPANYOL,"Callate");
        cv.put(BALI,"Oyong");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Dimana"); // FIELD 1
        cv.put(SPANYOL,"Donde");
        cv.put(BALI,"Dija");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Domba"); // FIELD 1
        cv.put(SPANYOL,"La oveja");
        cv.put(BALI,"Kambing");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Duduk"); // FIELD 1
        cv.put(SPANYOL,"Sientate");
        cv.put(BALI,"Domba");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Dulu"); // FIELD 1
        cv.put(SPANYOL,"En el pasado");
        cv.put(BALI,"Malu");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Elang"); // FIELD 1
        cv.put(SPANYOL,"Aguila");
        cv.put(BALI,"Sikep");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Enak"); // FIELD 1
        cv.put(SPANYOL,"Esta delicioso");
        cv.put(BALI,"Jaen sajang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Enggak"); // FIELD 1
        cv.put(SPANYOL,"No");
        cv.put(BALI,"Nggih");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Gadis"); // FIELD 1
        cv.put(SPANYOL,"Chica");
        cv.put(BALI,"Bajang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Gajah"); // FIELD 1
        cv.put(SPANYOL,"Elevante");
        cv.put(BALI,"Gajah");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Gereja"); // FIELD 1
        cv.put(SPANYOL,"La iglesia");
        cv.put(BALI,"Gereja");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Gigi"); // FIELD 1
        cv.put(SPANYOL,"Gigi");
        cv.put(BALI,"Gigi");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Gila"); // FIELD 1
        cv.put(SPANYOL,"Loco");
        cv.put(BALI,"Buduh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Guru");
        cv.put(SPANYOL,"Maestro");
        cv.put(BALI,"Guru");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Haus");
        cv.put(SPANYOL,"Sediento");
        cv.put(BALI,"Bedak");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Hidung"); // FIELD 1
        cv.put(SPANYOL,"Nariz");
        cv.put(BALI,"Cunguh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Hidup"); // FIELD 1
        cv.put(SPANYOL,"Vivo");
        cv.put(BALI,"Urip");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Ibu"); // FIELD 1
        cv.put(SPANYOL,"Madre");
        cv.put(BALI,"Meme");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Istri"); // FIELD 1
        cv.put(SPANYOL,"Esposa");
        cv.put(BALI,"Istri");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Itu"); // FIELD 1
        cv.put(SPANYOL,"Que");
        cv.put(BALI,"To");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Izin"); // FIELD 1
        cv.put(SPANYOL,"Permiso");
        cv.put(BALI,"Kelugran");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Jatuh"); // FIELD 1
        cv.put(SPANYOL,"Se cayo");
        cv.put(BALI,"Cepol");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Jendela"); // FIELD 1
        cv.put(SPANYOL,"La ventana");
        cv.put(BALI,"Jenela");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Jual"); // FIELD 1
        cv.put(SPANYOL,"Vendiendo");
        cv.put(BALI,"Adep");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kabar"); // FIELD 1
        cv.put(SPANYOL,"Las nocitias");
        cv.put(BALI,"Kabare");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kacamata"); // FIELD 1
        cv.put(SPANYOL,"Las gafas");
        cv.put(BALI,"Kacamata");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kakak"); // FIELD 1
        cv.put(SPANYOL,"Hermana");
        cv.put(BALI,"Beli");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kakek"); // FIELD 1
        cv.put(SPANYOL,"Abuelo");
        cv.put(BALI,"Kaki");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kaki"); // FIELD 1
        cv.put(SPANYOL,"Las piernas");
        cv.put(BALI,"Batis");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kambing"); // FIELD 1
        cv.put(SPANYOL,"Cabra");
        cv.put(BALI,"Domba");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kelinci"); // FIELD 1
        cv.put(SPANYOL,"Conejo");
        cv.put(BALI,"Kelinci");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kemana"); // FIELD 1
        cv.put(SPANYOL,"A donde");
        cv.put(BALI,"Kije");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kepala"); // FIELD 1
        cv.put(SPANYOL,"Jefe");
        cv.put(BALI,"Sireh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kerja"); // FIELD 1
        cv.put(SPANYOL,"Trabajo");
        cv.put(BALI,"Megae");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Klenteng"); // FIELD 1
        cv.put(SPANYOL,"Pagoda");
        cv.put(BALI,"Klenteng");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kucing"); // FIELD 1
        cv.put(SPANYOL,"Gato");
        cv.put(BALI,"Meong");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kuda");
        cv.put(SPANYOL,"Caballo");
        cv.put(BALI,"Jaran");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kurang");
        cv.put(SPANYOL,"Menos");
        cv.put(BALI,"Kirang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Kursi"); // FIELD 1
        cv.put(SPANYOL,"Silla");
        cv.put(BALI,"Tegakkan");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lama"); // FIELD 1
        cv.put(SPANYOL,"Viejo tiempo");
        cv.put(BALI,"Mekolo");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lapar"); // FIELD 1
        cv.put(SPANYOL,"Hambbriento");
        cv.put(BALI,"Seduk");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lari"); // FIELD 1
        cv.put(SPANYOL,"Huir");
        cv.put(BALI,"Ngacir");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lewat"); // FIELD 1
        cv.put(SPANYOL,"Mirar alrededor");
        cv.put(BALI,"Ngambahin");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lidah"); // FIELD 1
        cv.put(SPANYOL,"Lengua");
        cv.put(BALI,"Layah");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lubang"); // FIELD 1
        cv.put(SPANYOL,"El agujero");
        cv.put(BALI,"Song");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Lupa"); // FIELD 1
        cv.put(SPANYOL,"Olvidado");
        cv.put(BALI,"Engsap");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mainan"); // FIELD 1
        cv.put(SPANYOL,"Juguete");
        cv.put(BALI,"Pelalian");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Maju"); // FIELD 1
        cv.put(SPANYOL,"Adelante");
        cv.put(BALI,"Ngemaluang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Makan"); // FIELD 1
        cv.put(SPANYOL,"Comer");
        cv.put(BALI,"Ajeng");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Malam"); // FIELD 1
        cv.put(SPANYOL,"La noche");
        cv.put(BALI,"Lemeng");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mandi"); // FIELD 1
        cv.put(SPANYOL,"Tomar una ducha");
        cv.put(BALI,"Kayeh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Masjid"); // FIELD 1
        cv.put(SPANYOL,"La mezquita");
        cv.put(BALI,"Masjid");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mata"); // FIELD 1
        cv.put(SPANYOL,"El ojo");
        cv.put(BALI,"Aksi");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mati"); // FIELD 1
        cv.put(SPANYOL,"Morir");
        cv.put(BALI,"Perlaya");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mau"); // FIELD 1
        cv.put(SPANYOL,"Quiero");
        cv.put(BALI,"Nyak");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Meja"); // FIELD 1
        cv.put(SPANYOL,"Escritorio");
        cv.put(BALI,"Meja");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Minum"); // FIELD 1
        cv.put(SPANYOL,"Tomar una copa");
        cv.put(BALI,"Siup");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mobil"); // FIELD 1
        cv.put(SPANYOL,"El coche");
        cv.put(BALI,"Montor");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Motor"); // FIELD 1
        cv.put(SPANYOL,"cicleta");
        cv.put(BALI,"Motor");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mulut");
        cv.put(SPANYOL,"Boca");
        cv.put(BALI,"Bungut");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Mundur");
        cv.put(SPANYOL,"Retroceder");
        cv.put(BALI,"Nyatrek");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Murid"); // FIELD 1
        cv.put(SPANYOL,"Estudiante");
        cv.put(BALI,"Sisia");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Nahkoda"); // FIELD 1
        cv.put(SPANYOL,"Capitan");
        cv.put(BALI,"Nahkoda");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Negara"); // FIELD 1
        cv.put(SPANYOL,"El pais");
        cv.put(BALI,"Panegara");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Nenek"); // FIELD 1
        cv.put(SPANYOL,"Abuela");
        cv.put(BALI,"Niang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Nomor"); // FIELD 1
        cv.put(SPANYOL,"Numero");
        cv.put(BALI,"Nomor");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Obat"); // FIELD 1
        cv.put(SPANYOL,"Medicina");
        cv.put(BALI,"Tamba");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Ojek"); // FIELD 1
        cv.put(SPANYOL,"Taxi moto");
        cv.put(BALI,"Ojek");
                db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pacar"); // FIELD 1
        cv.put(SPANYOL,"Novia");
        cv.put(BALI,"Tunangan");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pagi"); // FIELD 1
        cv.put(SPANYOL,"Manana");
        cv.put(BALI,"Semeng");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Paman"); // FIELD 1
        cv.put(SPANYOL,"Tio");
        cv.put(BALI,"Iwa");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pasti"); // FIELD 1
        cv.put(SPANYOL,"Seguro");
        cv.put(BALI,"Seken");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Percaya"); // FIELD 1
        cv.put(SPANYOL,"Creelo");
        cv.put(BALI,"Percaye");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pergi"); // FIELD 1
        cv.put(SPANYOL,"Vete");
        cv.put(BALI,"Kaad");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Permisi"); // FIELD 1
        cv.put(SPANYOL,"Vete");
        cv.put(BALI,"Nunas lugra");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Petani"); // FIELD 1
        cv.put(SPANYOL,"Los agricultores");
        cv.put(BALI,"Tani");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pilot"); // FIELD 1
        cv.put(SPANYOL,"Piloto");
        cv.put(BALI,"Pilot");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pintu"); // FIELD 1
        cv.put(SPANYOL,"La puerta");
        cv.put(BALI,"Angkul-angkul");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pukul"); // FIELD 1
        cv.put(SPANYOL,"En punto");
        cv.put(BALI,"Cacak peleng");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Pulang"); // FIELD 1
        cv.put(SPANYOL,"Ir a casa");
        cv.put(BALI,"Mantuk");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Rusa"); // FIELD 1
        cv.put(SPANYOL,"El ciervo");
        cv.put(BALI,"Kidang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Salah"); // FIELD 1
        cv.put(SPANYOL,"Falso");
        cv.put(BALI,"Iwang, Pelih");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sampai");
        cv.put(SPANYOL,"Hasta");
        cv.put(BALI,"Anteg");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sapi");
        cv.put(SPANYOL,"Una vaca");
        cv.put(BALI,"Sampi");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Saya"); // FIELD 1
        cv.put(SPANYOL,"Yo");
        cv.put(BALI,"Tiang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sayur"); // FIELD 1
        cv.put(SPANYOL,"Verduuras");
        cv.put(BALI,"Jukut");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sedikit"); // FIELD 1
        cv.put(SPANYOL,"Un poco");
        cv.put(BALI,"Abedik");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sekarang"); // FIELD 1
        cv.put(SPANYOL,"Ahora");
        cv.put(BALI,"Mangkin");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sekolah"); // FIELD 1
        cv.put(SPANYOL,"Escuela");
        cv.put(BALI,"Pesraman");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Selamat"); // FIELD 1
        cv.put(SPANYOL,"Felicidades");
        cv.put(BALI,"Rahajeng");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Selesai"); // FIELD 1
        cv.put(SPANYOL,"Hecho");
        cv.put(BALI,"Suwud");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sepeda"); // FIELD 1
        cv.put(SPANYOL,"Becicleta");
        cv.put(BALI,"Sempeda");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Siang"); // FIELD 1
        cv.put(SPANYOL,"Mediodia");
        cv.put(BALI,"Tengai");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Siapa"); // FIELD 1
        cv.put(SPANYOL,"Quien");
        cv.put(BALI,"Nyen");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sini"); // FIELD 1
        cv.put(SPANYOL,"Aqui");
        cv.put(BALI,"Meriki");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sopir"); // FIELD 1
        cv.put(SPANYOL,"Conductor");
        cv.put(BALI,"Kusir");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sore"); // FIELD 1
        cv.put(SPANYOL,"Buenas tardes");
        cv.put(BALI,"Sanja");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Suami"); // FIELD 1
        cv.put(SPANYOL,"Marido");
        cv.put(BALI,"Kuren (an)");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Sudah"); // FIELD 1
        cv.put(SPANYOL,"Yo tengo");
        cv.put(BALI,"Suba");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tahu"); // FIELD 1
        cv.put(SPANYOL,"Saberlo");
        cv.put(BALI,"Nyawang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tangan"); // FIELD 1
        cv.put(SPANYOL,"Mano");
        cv.put(BALI,"Lengen");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tante"); // FIELD 1
        cv.put(SPANYOL,"Tia");
        cv.put(BALI,"Iwa");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tanya"); // FIELD 1
        cv.put(SPANYOL,"Preguntar");
        cv.put(BALI,"Metaken, metakon");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Telinga"); // FIELD 1
        cv.put(SPANYOL,"La oreja");
        cv.put(BALI,"Kupimg");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Teman"); // FIELD 1
        cv.put(SPANYOL,"Amigo");
        cv.put(BALI,"Kanti");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Terima");
        cv.put(SPANYOL,"Acceptar");
        cv.put(BALI,"Sanggra");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Terlambat");
        cv.put(SPANYOL,"Tarde");
        cv.put(BALI,"Kasep");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tidur"); // FIELD 1
        cv.put(SPANYOL,"Dormir");
        cv.put(BALI,"Sare");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tinggal"); // FIELD 1
        cv.put(SPANYOL,"Quedarse");
        cv.put(BALI,"Tinggal");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Tolol"); // FIELD 1
        cv.put(SPANYOL,"Tonto");
        cv.put(BALI,"Lengeh");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Truk"); // FIELD 1
        cv.put(SPANYOL,"Camion");
        cv.put(BALI,"Trek");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Uang"); // FIELD 1
        cv.put(SPANYOL,"Dinero");
        cv.put(BALI,"Pipis");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Udang"); // FIELD 1
        cv.put(SPANYOL,"Camarones");
        cv.put(BALI,"Udang");
        db.insert(KMS, "", cv);

        cv.put(INDONESIA,"Vihara"); // FIELD 1
        cv.put(SPANYOL,"El monasterio");
        cv.put(BALI,"Vihara");
        db.insert(KMS, "", cv);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        createTable(db);
        generateData(db);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        createTable(db);
        generateData(db);
    }
}
